# build environment
FROM node:12-alpine as build
WORKDIR /app
COPY package.json ./
RUN npm ci --silent
COPY . ./
RUN npm run build
RUN npm i -g serve
CMD [ "serve", "-s", "build", "-l", "80" ]