name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10.x, 12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: ${{ matrix.node_version }}
    
    - name: Install dependencies
      run: npm install
    
    - name: Build with npm
      run: npm run build --if-present
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10.x, 12.x]
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: ${{ matrix.node_version }}
    
    - name: Install dependencies
      run: npm install
    
    - name: Test with npm
      run: npm test -- --watchAll=false

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: 12.x
    
    - name: Install dependencies
      run: npm install

    - name: Run eslint
      uses: icrawl/action-eslint@v1    
